### ISSUE TITLE
ARROW2: support avro

### ISSUE THREAD

**Issue by houqp** [apache/arrow-datafusion#1061]
Avro integration needs to be fixed.

**Comment by Igosuki** [comment]
Is this about the dict issue or is it something else ?

**Comment by houqp** [comment]
This is something else, we need to port your avro implementation to https://github.com/jorgecarleitao/arrow2/tree/main/src/io/avro for #68 ;)

**Comment by houqp** [comment]
@Igosuki if you are interested in taking on this work, please coordinate with @jorgecarleitao .

**Comment by Igosuki** [comment]
@houqp will do

**Comment by jorgecarleitao** [comment]
The approach I took in `arrow2` was to not use `AvroValue` and work directly with the byte stream. The reason for this is that `AvroValue` takes bytes by value and not by reference, which implies that when we perform the conversion `File -> AvroValue -> Arrow` for a `Utf8` or `Binary`, we end up with the transformation `bytes -> AvroValue::String(String) -> Utf8Array`, performing an extra allocation _per item_.

Since the avro format is relatively simple to read from, I just implemented a reader from bytes directly to arrow. I [did not implemented it for all types](https://github.com/jorgecarleitao/arrow2/blob/main/src/io/avro/read/deserialize.rs#L131), only for the basic ones, but the idea stands.

So, if I understood, the goal is to generalize the parser to more types. Which ones are needed here?

**Comment by houqp** [comment]
I think struct and list are the main ones: https://github.com/apache/arrow-datafusion/blob/5cc4e9f53fab29e81ea7c98baac8ce277a0cb54a/datafusion/src/avro_to_arrow/arrow_array_reader.rs#L530

**Comment by Igosuki** [comment]
There is enum, array, dictionary (map), and logical types, these are almost
the same as parquet, as parquet a was meant to be a columnar version of
Avro.

**Comment by jorgecarleitao** [comment]
> as parquet a was meant to be a columnar version of Avro

ahhh, now it makes sense why they are so similar! Thanks a lot for sharing that.

I've implemented the remaining types here: https://github.com/jorgecarleitao/arrow2/pull/493 . We are missing `Struct` and `Decimal`.

**Comment by houqp** [comment]
@Igosuki I believe you have completed the migration for all avro related code right? Is there any left over for this issue?

**Comment by houqp** [comment]
Thanks @Igosuki for all your work on Avro :)
