### ISSUE TITLE
Error occurs when using union in query

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-datafusion#2083]
**Describe the bug**
in pg
```
postgres=# select 1 union select 2;
 ?column?
----------
        1
        2
(2 rows)
```
in df
```
❯ select 1;
+----------+
| Int64(1) |
+----------+
| 1        |
+----------+
1 row in set. Query took 0.002 seconds.
❯ select 2;
+----------+
| Int64(2) |
+----------+
| 2        |
+----------+
1 row in set. Query took 0.001 seconds.
❯ select 1 union select 2;
Plan("UNION ALL schemas are expected to be the same")

```
I think there two problems:
1. can not get result.
2. use `union` but get `UNION ALL`: i think they are totaly different 

related to #2032 
**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by Ted-Jiang** [comment]
I will try to fix this😊

**Comment by xudong963** [comment]
@Ted-Jiang I think there is a duplicate issue: https://github.com/apache/arrow-datafusion/issues/1818

**Comment by Ted-Jiang** [comment]
> @Ted-Jiang I think there is a duplicate issue: #1818

Thanks for your info❤️

**Comment by gandronchik** [comment]
It doesn't work in the current version.
`select 1 union select 2;`
ArrowError(ExternalError(Execution("Arrow error: External error: Internal error: Unsupported data type in hasher: Null. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker")))

`SELECT 1 a UNION ALL SELECT 2;`
```
+-------------+
| placeholder |
+-------------+
|             |
| 1           |
+-------------+
```

I fixed it. Now result is:
`select 1 union select 2;`
```
+----------+
| Int64(1) |
+----------+
| 2        |
| 1        |
+----------+
```

`SELECT 1 a UNION ALL SELECT 2;`
```
+---+
| a |
+---+
| 1 |
| 2 |
+---+
```
