### ISSUE TITLE
[Optimizer] Infer is not null predicate from `where clause`

### ISSUE THREAD

**Issue by jackwener** [apache/arrow-datafusion#2254]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
There are some predicate include implicit `is not null`.

```sql
select * from t1 where c1 > 0;  
-> 
select * from t1 where c1 > 0 and c1 is not null;
```

Why do this?

Expr in `select expr` and `where expr` is different.

Same `expr` in `select` don't include implicit `is not null`.

After this, 

We can do this

- eliminate self compare #2252
- convert outer join to inner join #1585
- eliminate Unsatisfiable Boolean Expressions #1716
- .... other about predicate

**Comment by jackwener** [comment]
Note: It isn't a `optimizer rule` !

It is because the following transformation can't terminate in Finite State Machine of rule.

```
select * from t1 where c1 > 0;  
-> 
select * from t1 where c1 > 0 and c1 is not null;
->
select * from t1 where c1 > 0 and c1 is not null and c1 is not null;
->
.....
```

So, In fact, this is a `rewrite` in planner build (Specifically, it is in `plan_selection`).

**Comment by alamb** [comment]
I think this is a *very* subtle area of SQL and it depends on how the expression is being used

For example, 

```sql
select * from t1 where c1 > 0;  
```
and 
```sql
select * from t1 where c1 > 0 and c1 is not null;
```

Are semantically equivalent (produce the same answers), but these are not:

```sql
select c1 > 0  from t1;
```
and
```sql
select c1 > 0 and c1 is not null from t1;
```

The reason is that the semantics of the `WHERE` clause are that only rows that evaluate to `true` are passed (if the row evaluates to `NULL` or `false` then they don't pass).

However, in general, you still have to handle the three way logic with `NULL` -- I am not at all convinced we do this entirely correctly in the expression simplification pass. We should probably have two modes: `used in where` and `used elsewhere` or something 🤔

**Comment by jackwener** [comment]
Yes, we just handle the expr in where.
This rewrite is from spark.

Andrew Lamb ***@***.***> 于 2022年4月19日周二 04:55写道：

**Comment by jackwener** [comment]
Great summary, this rewrite is from `spark`, I will read and consider carefully about this part. 

I want to do this just because some expr rewrite is include this problem.

**Comment by jackwener** [comment]
> I am not at all convinced we do this entirely correctly in the expression simplification pass. We should probably have two modes: used in where and used elsewhere or something 🤔

Yes, This is where the problem lies. Other optimizer rules depend on implicit `not null in where`, which must handle this problem. 

I think we should infer `is not null`, so other rule don't need to do infer `not null` but use directly `is not null` inferred by this rewrite. For example, convert outer join to left/right outer join or inner join can use `is not null` directly instead of match `compare operator`.
