### ISSUE TITLE
Type-coercion errors calling `round` function with two arguments

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2420]
**Describe the bug**
I am trying to run query `SELECT round(c1/3, 2) FROM aggregate_simple order by c1` where `c1` is a decimal. The query fails with `Coercion from [Decimal(29, 23), Int64] to the signature Uniform(1, [Float64, Float32]) failed.`.

**To Reproduce**
Run the query shown above.

**Expected behavior**
Query should work.

**Additional context**
None

**Comment by WinkerDu** [comment]
It seems `round` in df is an unary function with signature: `signature Uniform(1, [Float64, Float32])`
The possible approach to solve this issue is:
- Extends the `round` signature  to `one_of`
- Introduce the new `round` expression implementation  in `math_expressions.rs`

I can take this ticket as appropriate. @andygrove Can you assign this issue to me? Thank you.

**Comment by andygrove** [comment]
@WinkerDu I created https://github.com/apache/arrow-datafusion/pull/2503 to address this at the logical plan level but perhaps you could fix this in the physical planner to close this issue?

**Comment by viirya** [comment]
Unassigned this as it is more than 6 months ago.
