### ISSUE TITLE
Support "IS TRUE/FALSE" syntax

### ISSUE THREAD

**Issue by sarahyurick** [apache/arrow-datafusion#3159]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
A similar issue regarding "IS NOT TRUE/FALSE" syntax has already been opened (#2265), but it doesn't look like there is support for the "IS TRUE/FALSE" syntax either.

**Describe the solution you'd like**
Enum [datafusion](https://docs.rs/datafusion/2.0.0/datafusion/index.html)::[logical_plan](https://docs.rs/datafusion/2.0.0/datafusion/logical_plan/index.html)::[Expr](https://docs.rs/datafusion/2.0.0/datafusion/logical_plan/enum.Expr.html) should include functionality for IsTrue and IsFalse.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by alamb** [comment]
Looks like there is sqlparser support: https://docs.rs/sqlparser/latest/sqlparser/ast/enum.Expr.html#variant.IsTrue

Added in `0.18.0`:  https://github.com/sqlparser-rs/sqlparser-rs/blob/main/CHANGELOG.md#0180-2022-06-06

So this should be a fairly straightforward exercise -- note that `IS` and `=` are very subtlety differnt

Since we already have similar semantics for `IS` with the `IS NOT DISTINCT FROM` longer form syntax, I think this could potentially simply have the the SQL planner plan 

```sql
IS <expr>
``` 

as

```sql
is not distinct from <expr> as 'IS <expr.
```

Here is what postgres does

```sql
psql (14.4)
Type "help" for help.

alamb=# select null = null;
 ?column? 
----------
 
(1 row)

alamb=# select null IS null;
 ?column? 
----------
 t
(1 row)

alamb=# select null IS DISTINCT FROM null;
 ?column? 
----------
 f
(1 row)

alamb=# select null IS NOT DISTINCT FROM null;
 ?column? 
----------
 t
(1 row)
```

**Comment by sarahyurick** [comment]
Thanks for the response! I'll start working on this.

**Comment by alamb** [comment]
@sarahyurick  here is an example of doing something similar for `array`: 

https://github.com/apache/arrow-datafusion/pull/3122/files#diff-c01a34949db6258aa1593f011ecf90f62cbde406acd5cdbf8b9b60b970ace1cfR2372-R2374

```rust
        let fun = BuiltinScalarFunction::MakeArray;
        // follow postgres convention and name result "array"
        Ok(Expr::ScalarFunction { fun, args }.alias("array"))
```

So in other words you can probably do something like (untested):


```rust
Ok(binary_expr(left, Operator::IsNotDistinctFrom, right).alias("..."))
```

https://github.com/apache/arrow-datafusion/blob/ee55d89cbf20f4a6d17fe399c72d60dca6d67912/datafusion/expr/src/operator.rs#L59
