### ISSUE TITLE
Interval Literal doesn't work for timeunit less than millisecond

### ISSUE THREAD

**Issue by waitingkuo** [apache/arrow-datafusion#3204]
**Describe the bug**

**To Reproduce**

It works for millisecond
```bash
❯ select interval '1 month 0.001 second';
+-------------------------------------------------------+
| IntervalMonthDayNano("79228162514264337593544950336") |
+-------------------------------------------------------+
| 0 years 1 mons 0 days 0 hours 0 mins 0.1000000 secs   |
+-------------------------------------------------------+
1 row in set. Query took 0.001 seconds.
```

but doesn't work while the unit for second less than millisecond 

```bash
❯ select interval '1 month 0.0001 second';
+------------------------------------------------+
| IntervalYearMonth("1")                         |
+------------------------------------------------+
| 0 years 1 mons 0 days 0 hours 0 mins 0.00 secs |
+------------------------------------------------+
1 row in set. Query took 0.002 seconds.
```

**Expected behavior**

**Additional context**

**Comment by Jefffrey** [comment]
Seems to be because of this parsing:

https://github.com/apache/arrow-datafusion/blob/129654cd8466e7634bf186782c3d271541f0671e/datafusion/common/src/parsers.rs#L130-L161

Finest granularity is milliseconds, accumulated as an integer, hence fractions of that are silently ignored.

Could change this accumulator to nanoseconds, as `i64`, however this seems it would conflict with `ScalarValue::IntervalDayTime` which stores milliseconds as `i32`, compared to `ScalarValue::IntervalMonthDayNano` which does store nanoseconds.

Might need to change `ScalarValue::IntervalDayTime` to support nanoseconds perhaps? If want to be consistent between precision of `ScalarValue::IntervalMonthDayNano` and `ScalarValue::IntervalDayTime`
