### ISSUE TITLE
Paniced at to_timestamp_micros function when the timestamp is too large.

### ISSUE THREAD

**Issue by ZuoTiJia** [apache/arrow-datafusion#3832]
**Describe the bug**
Paniced at to_timestamp_micros function.

**To Reproduce**

```shell
DataFusion CLI v13.0.0
❯ SELECT to_timestamp_micros(9065525203050843594);
thread 'main' panicked at 'invalid or out-of-range datetime', 
.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.22/src/naive/datetime/mod.rs:131:18
```

**Additional context**
DataFusion 13.0

**Comment by retikulum** [comment]
Hi. I think this problem is about [chronos timestamp_nano function](https://github.com/chronotope/chrono/blob/a62da032f94b8553d8860d777ed0166b5f8396af/src/offset/mod.rs#L397) because it uses i64. Datafusion convert microsecond to nanosecond and passed it to timestamp_nano function. `9065525203050843594` microsecond is `9065525203050843594000` and it doesn't fit into i64 and overflowed. You can also see an example in [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6156756059d862af06621e9cf6478bbd). I guess the function call stack is followed:

- [to_timestamp_micros](https://github.com/apache/arrow-datafusion/blob/c59a76754e7e45063cb51c273f2a53aa325676a4/datafusion/physical-expr/src/datetime_expressions.rs#L152)
- [string_to_timestamp_nanos_shim](https://github.com/apache/arrow-datafusion/blob/c59a76754e7e45063cb51c273f2a53aa325676a4/datafusion/physical-expr/src/datetime_expressions.rs#L129)
- [arrow's string_to_timestamp_nanos](https://github.com/apache/arrow-rs/blob/master/arrow/src/compute/kernels/cast_utils.rs#L69)
- [chrono's timestamp_nanos](https://github.com/chronotope/chrono/blob/a62da032f94b8553d8860d777ed0166b5f8396af/src/offset/mod.rs#L397)

It seems interesting case but I am not sure about the solution.

**Comment by waitingkuo** [comment]
https://github.com/chronotope/chrono/blob/main/src/naive/datetime/mod.rs#L117

`from_timestamp` will be deprecated since 0.4.23.
i think we could change it to `from_timestamp_opt` and notify the user it's out-of-range

**Comment by waitingkuo** [comment]
> I think it is not releated to this issue but datafusion uses `from_timestamp` function in following line:
> 
> https://github.com/apache/arrow-datafusion/blob/f93642fd7782b0d530a5bff0fecec020b34e9bd1/datafusion/physical-expr/src/expressions/datetime.rs#L304
> 
> So we also need to fix it. If I am wrong, could you also suggest me tips about how to debug/analyze these bugs?

@retikulum yes, i think we need to fix it as well.

@alamb @avantgardnerio 
do you think we should eventually move these datetime arithmetic functions into arrow-rs?

**Comment by avantgardnerio** [comment]
When chrono:0.4.23 is out we can kill all these:

```
        ScalarValue::IntervalDayTime(Some(i)) => add_day_time(prior, *i, sign),
        ScalarValue::IntervalYearMonth(Some(i)) => shift_months(prior, *i * sign),
        ScalarValue::IntervalMonthDayNano(Some(i)) => add_m_d_nano(prior, *i, sign),
```

**Comment by avantgardnerio** [comment]
Presently we can't remove them yet because there is no Timestamp + Months, only Date + months in 0.4.22.

**Comment by alamb** [comment]
> do you think we should eventually move these datetime arithmetic functions into arrow-rs?

Yes, I do think eventually the date/time arithmetic should be moved into arrow-rs kernels

**Comment by Jefffrey** [comment]
Issue seems to be resolved now, doesn't panic but returns error:

```bash
DataFusion CLI v15.0.0
❯ SELECT to_timestamp_micros(9065525203050843594);
+-----------------------------------------------+
| totimestampmicros(Int64(9065525203050843594)) |
+-----------------------------------------------+
| ERROR CONVERTING DATE                         |
+-----------------------------------------------+
1 row in set. Query took 0.002 seconds.
❯
```

**Comment by alamb** [comment]
Thank you for checking @Jefffrey
