### ISSUE TITLE
JoinSelection Rule to choose physical join implementation: HashJoin(Partitioned or CollectLeft)  or SortMergeJoin base on Stats

### ISSUE THREAD

**Issue by mingmwang** [apache/arrow-datafusion#4139]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mingmwang** [comment]
@alamb @andygrove @isidentical @Dandandan @yahoNanJing 
I plan to add a new physical rule for physical join implementation selection based on stats.

The basic idea is if one of side(left or right) is small enough(threshold on size or row count, for example 10M), will choose HashJoin:CollectLeft.
Else if either side exceed that threshold but still smaller than hash join threshold(estimated_size/partition_count <= 128M for example), will choose  HashJoin: Partitioned.
Otherwise choose SortMergeJoin.

Please share your thoughts.

**Comment by Dandandan** [comment]
Sounds like a good plan.

For hash join, probably needs some benchmarking to figure out good defaults and avoid performance degradation. `CollectLeft` limits the amount of parellization on the left side: building the hash table is relatively expensive and is done (at least currently) in a single thread. In quite a few cases it might be more beneficial to do a (local) hash repartitioning which is relatively cheap.
It also depends on the size of the probe/right side: if that's e.g. >100x as big as the left side it might be beneficial to avoid the hash repartitioning on the right side by switching to `CollectLeft`.

**Comment by alamb** [comment]
I agree with @Dandandan  that doing some benchmarking on sort merge join is likely a good idea. I don't think we have much at the moment as it is never used.

What I think would be an ideal solution, though maybe harder to implement, is to *NOT* decide between has or sort merge join at plan time, but to decide at runtime

So that would involve starting out using HashJoin but if the hash table spilled (or exceeded some size threshold) sort/spill it and then switch to sort-merge-join
