### ISSUE TITLE
scalar function `round` ignores second parameter

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#4191]
**Describe the bug**

`round` accepts two arguments, but is also defined as a unary function. The second parameter is ignored.

```
❯ select round(3.141592, 0);
+-----------------------------------+
| round(Float64(3.141592),Int64(0)) |
+-----------------------------------+
| 3                                 |
+-----------------------------------+
1 row in set. Query took 0.000 seconds.

❯ select round(3.141592, -2);
+------------------------------------+
| round(Float64(3.141592),Int64(-2)) |
+------------------------------------+
| 3                                  |
+------------------------------------+
1 row in set. Query took 0.000 seconds.

❯ select round(3.141592, 2);
+-----------------------------------+
| round(Float64(3.141592),Int64(2)) |
+-----------------------------------+
| 3                                 |
+-----------------------------------+
1 row in set. Query took 0.000 seconds.
```

**To Reproduce**
See above

**Expected behavior**
I expect the behavior to be consistent with Postgres `round(v numeric, s int)`. User guide will also need updating.

**Additional context**
Related to https://github.com/apache/arrow-datafusion/issues/2420

**Comment by HaoYang670** [comment]
Not sure, but I wonder could we support this is logical phase? 
Given the following 2 lemmas:
```coq
1. forall source: FloatArray, round(source) = round(source, 0)
2. forall source: FloatArray n: IntArray,
        round(source, n) = div(
                              round(mul(
                                      source, 
                                      pow(10, n))), 
                              pow(10, n))
```
we can unfold the `round` function in the logical plan stage and don't need to modify the physical stage.

One concern here is that `Decimal` type might be better than `Float` type because we've found some corner cases in floating point multiplication and division:

**Comment by DDtKey** [comment]
Just wondering if anyone is working on it? It's relevant for current version. I see the same behaviour

**Comment by HaoYang670** [comment]
I've pushed a draft PR (#4234) to unfold the `round` function with 2 args in logical plan.
But it seems like not a good solution because it would reduce the extensibility of the logical optimizer.

Based on Andy's comment (https://github.com/apache/arrow-datafusion/pull/4234#discussion_r1024287522) we should either support this or return an error in the physical plan.

> Just wondering if anyone is working on it?

No, I guess.
