### ISSUE TITLE
`having` shouldn't include alias in projection

### ISSUE THREAD

**Issue by jackwener** [apache/arrow-datafusion#4556]
**Describe the bug**

When I try to refactor the planner having, I find the `having` planner is wrong.

1147 line in planner.rs
```rust
// This step "dereferences" any aliases in the HAVING clause.
```

In fact, `having` can't access the projection alias (because `having` is before the `select`).
having is `just` filter group results, it can't get alias in projection.

for example:
```sql
-- create
CREATE TABLE EMPLOYEE (
  empId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  dept TEXT NOT NULL
);
-- insert
INSERT INTO EMPLOYEE VALUES (0001, 'Clark', 'Sales');
-- fetch 
select empId, length(name) as l FROM EMPLOYEE group by empId having l > 10;

psql:commands.sql:15: ERROR:  column "l" does not exist
LINE 1: ...ength(name) as l FROM EMPLOYEE group by empId having l > 10;
```

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by jackwener** [comment]
I will try to fix it🚀
In the future, I also do more enhancement for `planner`.
It looks like planner can be implemented a little better, I think polish the framework is greater than add many patch to fix bugs.

**Comment by jackwener** [comment]
`standard sql` disallow `groupby` or `having` use the alias in `select list`.

But, pg allow `groupby` use alias in `select list` but disallow `having` use alias.

so strange things.

```sql
-- create
CREATE TABLE EMPLOYEE (
  empId INTEGER PRIMARY KEY,
  age INTEGER NOT NULL,
  name TEXT NOT NULL
);

-- insert
INSERT INTO EMPLOYEE VALUES (0001, 0020, 'Sales');

--ok
select max(empId), age as a from EMPLOYEE group by a;
--failed
select max(empId), age as a from EMPLOYEE group by a > 3;

-- ok
select max(empId), (age + empId) as a from EMPLOYEE group by a;
-- failed
select max(empId), (age as a + empId) as a from EMPLOYEE group by (a + empId);
```

**Comment by jackwener** [comment]
cc @Dandandan @alamb @andygrove .

I don't know if this is a mistake or a feature and how we should do it better.

**Comment by mingmwang** [comment]
@jackwener Maybe you can refer to this

https://docs.snowflake.com/en/sql-reference/constructs/having.html

Per SnowFlake's doc, HAVING should apply to expressions produced by the GROUP BY.
GROUP BY can include Alias. Today DataFusion does not merge the adjacent PROJECT and GROUP BY. In future we might
add a rule to collapse the adjacent PROJECT and GROUP BY Aggregation, so that the GROUP BY exprs will include Alias.

Some other docs for you to refer about the evaluation ordering of operators:

https://docs.snowflake.com/en/sql-reference/constructs/qualify.html
https://docs.teradata.com/r/Teradata-VantageTM-SQL-Data-Manipulation-Language/March-2019/Select-Statements/QUALIFY-Clause/Usage-Notes/Evaluation-Order-of-WHERE-GROUP-BY-and-QUALIFY-Clauses

**Comment by alamb** [comment]
As @mingmwang  -- exprs in the `HAVING` clause should only be able to reference the logical output of the GROUP BY clause 👍

**Comment by mingmwang** [comment]
> As @mingmwang -- exprs in the `HAVING` clause should only be able to reference the logical output of the GROUP BY clause 👍

@yahoNanJing

**Comment by alamb** [comment]
@jackwener  what else is needed other than https://github.com/apache/arrow-datafusion/pull/4579 to close this issue?
