### ISSUE TITLE
Failed to run SQL that uses full outer join with a boolean literal join condition

### ISSUE THREAD

**Issue by yukkit** [apache/arrow-datafusion#5382]
**Describe the bug**

**To Reproduce**

```shell
DataFusion CLI v18.0.0
❯ create table test1(intt int, inttt int) as select 1 as intt, 2 as inttt;
0 rows in set. Query took 0.017 seconds.
❯ create table test2(intt int, inttt int) as select 1 as intt, 2 as inttt;
0 rows in set. Query took 0.006 seconds.
❯ SELECT *
FROM test2
        FULL JOIN test1 ON true;
Execution error: Build left right indices error
❯ 
```

**Expected behavior**

return the correct record

**Additional context**

**Comment by jackwener** [comment]
fail in `build_batch_from_indices`.

cc @liukun4515 @ygf11

**Comment by ygf11** [comment]
Seems it is caused by trying to create RecordBatch with empty schema.
https://github.com/apache/arrow-datafusion/blob/c676d1026f8fa25c1495ec139b8a379ce1f2f86b/datafusion/core/src/physical_plan/joins/utils.rs#L823

The row count is inferred from columns, but the columns is also empty here.

We can use `RecordBatch::try_new_with_options` with specifying the row count.
https://github.com/apache/arrow-rs/blob/e7eb304dac442a943c434f8ea248de909f82aa88/arrow-array/src/record_batch.rs#L107-L113
