### ISSUE TITLE
Join two tables with the same schema, then union throws `SchemaError(DuplicateUnqualifiedField )`

### ISSUE THREAD

**Issue by ZuoTiJia** [apache/arrow-datafusion#5410]
**Describe the bug**
Join two tables with the same schema, then union throws `SchemaError(DuplicateUnqualifiedField )`

**To Reproduce**
```sql
create table ta(a bigint) as values(1);
create table tb(a bigint) as values(2);
select * from ta join tb on true
    union all
select * from ta join tb on true;
```
SchemaError(DuplicateUnqualifiedField { name: "a" })

**Expected behavior**
query sucess.

**Additional context**
datafusion v18.0.0

**Comment by Jefffrey** [comment]
Issue seems to be here:

https://github.com/apache/arrow-datafusion/blob/5ffa8d78f7e5796fa7c2f98b19346576ab2a4bb8/datafusion/expr/src/logical_plan/builder.rs#L1085-L1111

Specifically where it strips the qualifier from the generated `DFField`

A solution could be to grab the left field qualifier here instead of wiping it.

**Comment by yukkit** [comment]
> Issue seems to be here:
> 
> https://github.com/apache/arrow-datafusion/blob/5ffa8d78f7e5796fa7c2f98b19346576ab2a4bb8/datafusion/expr/src/logical_plan/builder.rs#L1085-L1111
> 
> Specifically where it strips the qualifier from the generated `DFField`
> 
> A solution could be to grab the left field qualifier here instead of wiping it.

I agree with you
