### ISSUE TITLE
`from_qualified_name` bug when column name starts with a number

### ISSUE THREAD

**Issue by sarahyurick** [apache/arrow-datafusion#5426]
@ayushdg pointed out that when doing `Column::from_qualified_name("table_pq.a")`, it uses SQLParser's `Tokenizer` to generate:
```
[
  Word(
    Word { value: "table_pq", quote_style: None, keyword: NoKeyword }), 
    Period, 
    Word(Word { value: "a", quote_style: None, keyword: NoKeyword }
  )
]
```

as expected, which can then return a `Column { relation: "table_pq", name: "a" }`. However, if the column name starts with a number, like `Column::from_qualified_name("table_pq.1b")`, we get:
```
[
  Word(
    Word { value: "table_pq", quote_style: None, keyword: NoKeyword }), 
    Number(".1", false), 
    Word(Word { value: "b", quote_style: None, keyword: NoKeyword }
  )
]
```

and we're not able to return the expected result (it ends up having to return a `Column { relation: None, name: "table_pq.1b" }` instead of a `Column { relation: "table_pq", name: "1b" }`).

I was wondering if it would be better to fix this on the SQLParser side, or if it would make more sense to add extra logic for `from_qualified_name` on the DataFusion side instead?

**Comment by Jefffrey** [comment]
I think this might actually be intentional. The SQL dialect that DataFusion uses intentionally disallows having numbers start an identifier, and if you want to have that case then you'd need to quote the identifier, like so:

`Column::from_qualified_name("table_pq.\"1b\"")`

To indicate that it is an identifier as a whole, not a number preceding a word.

Postgres treats such identifiers in a similar way.

**Comment by sarahyurick** [comment]
Thanks! This makes sense to me.

Since Dask-SQL wants to support column names starting with a number, we can just make some changes on our side rather than on the DataFusion side.
