### ISSUE TITLE
parquet-test-utils Circular Crate Dependency

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-datafusion#5453]
**Describe the bug**

`parquet-test-utils` depends on `datafusion` which in turn has a dev-dependency on `parquet-test-utils`. This is not ideal as it results in repeated recompilation, when running tests.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
Maybe I could lift the stuff in datafusion dev that depends on parquet-test-utils into its own test. Let me check

**Comment by alamb** [comment]
@tustvold  the reason is that the code to generate test parquet files is shared between the parquet benchmark and the parquet test

https://github.com/apache/arrow-datafusion/blob/49473d68bee42208aec0f5ad5be6326c1ed11661/benchmarks/src/bin/parquet_filter_pushdown.rs#L25

https://github.com/apache/arrow-datafusion/blob/49473d68bee42208aec0f5ad5be6326c1ed11661/datafusion/core/tests/parquet/filter_pushdown.rs#L39

The only thing I can think to do is to make a new crate (`datafusion-tests` for example) to mirror `datafusion-examples` that both depend `parquet-test-utils`

What do you think?

**Comment by tustvold** [comment]
> code to generate test parquet files is shared between the parquet benchmark and the parquet test

This might be a naive question but why does this code depend on datafusion, the original access-log-gen didn't? Could we decouple it?

**Comment by alamb** [comment]
Proposed fix https://github.com/apache/arrow-datafusion/pull/5506
