### ISSUE TITLE
Move some rules and code into Analyzer

### ISSUE THREAD

**Issue by jackwener** [apache/arrow-datafusion#5681]
### Describe the solution you'd like

Move some rules and code into Analyzer

- InlineTableScan
- TypeCoercion
- ...

**Comment by mslapek** [comment]
This is a very important feature. 🪜

Moving `TypeCoercion` into pre-optimizer phase would allow to avoid "Mismatch between schema and batches", like #5733 (and possibly #5695).

`TypeCoercion` being **an optimizer** is a broken concept - because optimizers cannot change the final schema of the logical plan.

What is more, `Expr::Case` has an assumption, that all inputs are **already** coerced.
