### ISSUE TITLE
Remove AggregateExpr::create_accumulator

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-datafusion#7112]
### Is your feature request related to a problem or challenge?

`AggregateExpr` currently provides both the `ScalarValue` based `Accumulator` and the new `GroupsAccumulator` interface. With an additional `groups_accumulator_supported` to indicate if `GroupsAccumulator` is supported.

This is unfortunate as it forces us to keep two accumulator implementations for each expression, which is not only wasteful but introduces the possibility of inconsistency between the two implementations 

### Describe the solution you'd like

Change `AggregateExpr::create_accumulator` to return `GroupsAccumulator`, and remove `groups_accumulator_supported` and `create_groups_accumulator`. Implementations that currently only have an `Accumulator` based implementation can return a `GroupsAccumulatorAdapter`, which is ultimately what `GroupedHashAggregateStream` will do anyway

### Additional context

This blocks https://github.com/apache/arrow-datafusion/issues/6842

**Comment by alamb** [comment]
I think updating `AggregateExpr` which is largely an internal implementation detail of DataFusion, to better communicate what is supported and what is not makes a lot of sense to me.

I think there are two accumulators now because Accumulator has an API to do retractable updates (incremental updates)
Accumulator is part of the public API so I don't think it can / should be removed

**Comment by alamb** [comment]
The only thing that might be tricky with this proposal is making sure the right implementation is provided for accumulators that can do retractable updates (like sum and count)
