### ISSUE TITLE
[BUG] CAST Decimal gives incorrect result

### ISSUE THREAD

**Issue by comphead** [apache/arrow-datafusion#7121]
### Describe the bug

CAST Decimal gives incorrect result

### To Reproduce

Spark/PG
```
select cast(6.4053151420411946063694043751862251568 as decimal(38,37))

6.4053151420411946063694043751862251568
```
DF
```
❯ select cast(6.4053151420411946063694043751862251568 as decimal(38,37));
+-----------------------------------------+
| Float64(6.405315142041195)              |
+-----------------------------------------+
| 6.4053151420411954619510965656866521088 |
+-----------------------------------------+
```

### Expected behavior

Should cast correctly

**Comment by comphead** [comment]
I'll check that

**Comment by viirya** [comment]
I'm not sure if this is a bug.

Actually, even you do something like:

```
❯ select 6.4053151420411946063694043751862251568;
+----------------------------+
| Float64(6.405315142041195) |
+----------------------------+
| 6.405315142041195          |
+----------------------------+
1 row in set. Query took 0.005 seconds.
```

You can see that you still cannot get full precision of the input floating point.

It is more like the precision limit instead of an incorrect result.

Further, if you look at Spark, `6.4053151420411946063694043751862251568` is treated as decimal, instead of float64

```
scala> sql("select 6.4053151420411946063694043751862251568").printSchema
root
 |-- 6.4053151420411946063694043751862251568: decimal(38,37) (nullable = false)
```

So actually in Spark you just cast decimal to decimal?

But in DataFusion, it is float64:

```
❯ explain select 6.4053151420411946063694043751862251568;
+---------------+------------------------------------------------------------------------+
| plan_type     | plan                                                                   |
+---------------+------------------------------------------------------------------------+
| logical_plan  | Projection: Float64(6.405315142041195)                                 |
|               |   EmptyRelation                                                        |
| physical_plan | ProjectionExec: expr=[6.405315142041195 as Float64(6.405315142041195)] |
|               |   EmptyExec: produce_one_row=true                                      |
|               |                                                                        |
+---------------+------------------------------------------------------------------------+
2 rows in set. Query took 0.006 seconds.

```

It explains why casted result is the exactly same as input because there will be precision loss when casting floating-point value to decimal.

Then, let's force Spark to treat input value as float64?

```
scala> sql("select cast(6.4053151420411946063694043751862251568d as decimal(38,37))").collect()
res13: Array[org.apache.spark.sql.Row] = Array([6.4053151420411950000000000000000000000])
```

You can see that now Spark also returns a precision loss decimal.

**Comment by comphead** [comment]
I would still treat this as a bug, my vision the problem is DF cannot identify correctly decimal as a input and does implicit conversion to the f64 which is not expected.

Both Postgres and Spark returns correct result for 
```
select 6.4053151420411946063694043751862251568 + 1;

7.4053151420411946063694043751862251568
```

whereas DF likely does unneccessary cast and thus loss of precision

```

❯ select 6.4053151420411946063694043751862251568 + 1;
+---------------------------------------+
| Float64(6.405315142041195) + Int64(1) |
+---------------------------------------+
| 7.405315142041195                     |
+---------------------------------------+
1 row in set. Query took 0.057 seconds.
```

**Comment by viirya** [comment]
Then it is a question about what type of value should DataFusion parse from a literal like `6.4053151420411946063694043751862251568`, it should be currently float64, or decimal like Spark?

This could be discussed.

I'm not sure if it is designed by intention or just a mistake (bug?).

Just to clarify that this is not a bug that DataFusion cast produces an incorrect result. Actually the cast result is correct as it treats the input as float64 instead of decimal. Otherwise, it might be confused for others who look for the root cause in cast function but actually it is not there.

**Comment by Dandandan** [comment]
There is a config in DF whether to parse floating numbers as decimal by default, it was disabled earlier because of issues, but maybe by now we should enable it by default.

**Comment by Dandandan** [comment]
https://github.com/apache/arrow-datafusion/blob/55930fbffe34611e42676c52a31f7e90ccd77ca5/datafusion/sql/src/planner.rs#L62

**Comment by comphead** [comment]
Thanks @Dandandan 

```
❯ set datafusion.sql_parser.parse_float_as_decimal=true;

❯ select cast(6.4053151420411946063694043751862251568 as decimal(38,37)) + 1;
+---------------------------------------------------------------------------+
| Decimal128(Some(64053151420411946063694043751862251568),38,37) + Int64(1) |
+---------------------------------------------------------------------------+
| 7.4053151420411946063694043751862251568                                   |
+---------------------------------------------------------------------------+
```
