### ISSUE TITLE
Document SQL operators (like `@>` and `~`)

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#7153]
### Is your feature request related to a problem or challenge?

While reviewing https://github.com/apache/arrow-datafusion/pull/6885#pullrequestreview-1554850720 to add support for `@>` and `<@` array containment operators, I found that there is no documentation on the list of supported datafusion operators

### Describe the solution you'd like

I would like documentation for the operators listed in https://github.com/apache/arrow-datafusion/blob/e02ed51b880d09f2156bd192d283aef75cab04b7/datafusion/expr/src/operator.rs#L29-L80

In a new page of the datafusion SQL guide https://arrow.apache.org/datafusion/user-guide/sql/index.html

### Additional context

This would be a great way to get introduced to datafusion, fire up the CLI to test it out, and help the community so marking it as a good first issue

**Comment by palash25** [comment]
I will try to submit a PR for this

**Comment by spaydar** [comment]
Hi @alamb , I'm new to the project and am trying to push a feature branch I've started work on but am getting the following error message:
```
$ git push --set-upstream origin 7153                                                                                     
ERROR: Permission to apache/arrow-datafusion.git denied to spaydar.                                                                                                     
fatal: Could not read from remote repository.                                                                                                                           
                                                                                                                                                                         
Please make sure you have the correct access rights                                                                                                                     
and the repository exists.
```
I didn't see anything in the [Contributor Guide](https://arrow.apache.org/datafusion/contributor-guide/index.html) about needing access granted to push feature branches. `git pull` works fine. Any tips on how to resolve this?

**Comment by palash25** [comment]
@spaydar that is because you are pushing to the origin repo for which you don't have write access. You will need to fork this repo and then set the url of your fork as a remote. Something like this `git remote add fork <fork-url>`

Then push to that remote instead. Once you do that you can create a PR. `git push fork <branch-name>`

And please always comment on an issue before you start work on it. As you can see I had already commented on this a few hours before your comment and started some work. If I had seen your comment I wouldn't try to claim this. This avoids duplication of work.

**Comment by spaydar** [comment]
@palash25 Thank you for your explanation of how to fork and push my code. This is my first time contributing to OSS -- do most OSS projects prefer forking the repo over feature branch development within the same repo?

Sorry for the duplication of work 🙇‍♂️️ I hope I did not waste too much of your time. Next time I'll comment before I start working on an issue.

**Comment by palash25** [comment]
>  do most OSS projects prefer forking the repo over feature branch development within the same repo?

yes because OSS projects can get 100s of contributors and it is a low trust environment so they can't give out write access to new people. You only get write access when you become a maintainer. So you should always clone and `git pull` from the origin repo but always push to your fork

>  I hope I did not waste too much of your time.

don't worry i had just  put in 10 mins of work into my branch.

**Comment by alamb** [comment]
Thank you @palash25 and @spaydar  -- good learnings all around on this ticket. @palash25's observations and analysis is correct
