### ISSUE TITLE
aggregate sqllogictest fails

### ISSUE THREAD

**Issue by doki23** [apache/arrow-datafusion#7764]
### Describe the bug

I run the sqllogictest at latest commit of the main branch but it failed.
> cargo test --test sqllogictests

the result is
> External error: query result mismatch:
[SQL] select trace_id, MIN(timestamp) from traces group by trace_id order by MIN(timestamp) asc limit 4;
[Diff] (-expected|+actual)
    NULL 0
    b 0
\-   c 1
\-   a 1
\+   a 1
\+   c 1
at test_files/aggregate.slt:2357

### To Reproduce

run the command
> cargo test --test sqllogictests

my laptop is macbook pro m1, and the commit is `c0409a7b`

### Expected behavior

pass the test

**Comment by alamb** [comment]
Thanks @doki23  -- it looks to me like the problem is that the output of the query is not deterministic -- namely that `min(timestamp)` is not distinct so `ORDER BY MIN(timestamp)` can return either order

I recommend we update the data used so that the min timestamp is distinct (aka add a row like `('a', 0)` or something
