### ISSUE TITLE
DataFrame::write_table return type is documented incorrectly

### ISSUE THREAD

**Issue by mlilback** [apache/arrow-datafusion#8487]
### Describe the bug

The [documentation](https://docs.rs/datafusion/latest/datafusion/dataframe/struct.DataFrame.html#method.write_table) for DataFrame:write_table says `returning the count of rows written` but it returns `Result<Vec<RecordBatch>, DataFusionError>`.

**Comment by devinjdangelo** [comment]
The Vec<RecordBatch> that is returned will contain a single RecordBatch with a single Row and Column, which is the count of rows written. 

Result<Vec<RecordBatch>> is the return type since under the hood write table calls collect() which collects a stream of RecordBatchs into a Vec. It just so happens this specific plan will only return a single recordbatch with a single value.

Since we know InsertExec will only return a single value, we could extract that value and cast to usize. Alternatively, we could expand the documentation to make this more clear.

**Comment by devinjdangelo** [comment]
@mlilback I opened a PR to update this documentation to hopefully make it more clear!

This method ultimately runs an execution plan returned by an arbitrary `dyn TableProvider`, so  it is true we should not state so plainly that this method will always return the count of rows inserted. It depends on the specific TableProvider registered for the table passed. 

I updated the docs to reflect this nuance in the PR.
