### ISSUE TITLE
cargo cannot install datafusion-cli with version 5

### ISSUE THREAD

**Issue by capacman** [apache/arrow-datafusion#883]
**Describe the bug**
In datafusion 4 i can install datafusion-cli just by installing datafusion via cargo but now when i want to install/update datafusion it says
```sh
cargo install datafusion                 
    Updating `http://localhost:8080/index` index
  Downloaded datafusion v5.0.0 (registry `http://localhost:8080/index`)
  Downloaded 1 crate (336.4 KB) in 0.48s
error: there is nothing to install in `datafusion v5.0.0`, because it has no binaries
`cargo install` is only for installing programs, and can't be used with libraries.
To use a library crate, add it as a dependency in a Cargo project instead
```
**To Reproduce**
just issue command
`cargo install datafusion`

**Expected behavior**
Install datafusion-cli with command `cargo install datafusion`

**Comment by houqp** [comment]
datafusion-cli has been moved into its own crate in 5.0.0 release, but we haven't released a new version of the cli yet with the 5.0.0 release.

@andygrove @alamb we don't have datafusion-cli name reserved in crates.io, do we want to publish it to crates.io? Or do you expect us to only release binaries for the cli going forword?

**Comment by andygrove** [comment]
I think we should be publishing the crate. We cannot release from the source tarball that was voted on because it has a snapshot version and also a path dependency on DataFusion, so we'll need to fix this for the next release.

On a related note, I'd like the CLI to support Ballista as well, and there is the choice to extend datafusion-cli or create a new ballista-cli. See https://github.com/apache/arrow-datafusion/issues/886. It would be good to make a decision on approach before we start reserving crate names.

**Comment by houqp** [comment]
https://github.com/apache/arrow-datafusion/pull/885 has datafusion-cli dependency fixed.

**Comment by alamb** [comment]
I agree that publishing a separate `datafusion-cli` crate is the way to go here. 👍

**Comment by Dandandan** [comment]
Yes, agreed 👍

**Comment by houqp** [comment]
this is now blocked by https://github.com/apache/arrow-datafusion/issues/1332
