### ISSUE TITLE
Add GitHub workflow to close stale PRs

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#8865]
### Is your feature request related to a problem or challenge?

We currently have 116 open PRs, some of them from around one year ago. This creates an additional maintenance burden for reviewers and also can result in older active PRs being ignored.

### Describe the solution you'd like

We could use this GitHub action to automatically close PRs that are inactive for 60 days:

https://github.com/marketplace/actions/close-stale-issues

**Comment by andygrove** [comment]
@alamb WDYT?

**Comment by alamb** [comment]
> @alamb WDYT?

I think that would be super helpful 🙏  and I think it would be nice to have a policy that just closes stale PRs rather than doing it manually (which requires I think writing down some explanation of what is needed). 

Maybe we can also write up a section in the docs (I can maybe help) about how PRs are prioritized for reviews?

Here are some filters I have been using
* Read to merge: https://github.com/apache/arrow-datafusion/pulls?q=is%3Apr+is%3Aopen+review%3Aapproved+-is%3Adraft
* Need review https://github.com/apache/arrow-datafusion/pulls?q=is%3Apr+is%3Aopen+-review%3Aapproved+-is%3Adraft+

**Comment by Tangruilin** [comment]
@alamb are there someone working with this?
If not, I think I can work with it.
this is meaningful!!!

**Comment by alamb** [comment]
Thank you @Tangruilin  -- this would be really helpful. I agree it is meaningful. No one is working on it that i know of

**Comment by andygrove** [comment]
I plan on picking this up if nobody beats me to it.
