### ISSUE TITLE
Evaluates CASE branches even if their WHEN clause is false

### ISSUE THREAD

**Issue by tv42** [apache/arrow-datafusion#8909]
### Describe the bug

Datafusion evaluates `CASE ... WHEN ... THEN` expressions even for non-true branches, and bubbles up runtime errors from them.

This is wrong because the `CASE` could be explicitly protecting against the divide-by-zero case, and differs from other sql engines.

### To Reproduce

```console
❯ SELECT CASE 1 WHEN 2 THEN 42/0 END;
Optimizer rule 'simplify_expressions' failed
caused by
Arrow error: Divide by zero error
```

### Expected behavior

I expected the `CASE` to evaluate to `NULL`, as none of its `WHEN` branches were true and it did not have an `ELSE`.

Compare to SQLite:

```console
sqlite> .nullvalue NULL
sqlite> SELECT CASE 1 WHEN 2 THEN 42/0 END;
NULL
```

Compare to Postgres:

```console
postgres=# \pset null 'NULL'
Null display is "NULL".
postgres=# SELECT CASE 1 WHEN 2 THEN 42/0 END;
 case
------
 NULL
(1 row)
```

**Comment by alamb** [comment]
Possible related https://github.com/apache/arrow-datafusion/pull/8833 / https://github.com/apache/arrow-datafusion/issues/8814 

cc @haohuaijin  and @liukun4515

**Comment by haohuaijin** [comment]
It looks like related to the `simplify_expressions` rule because the `simplify_expressions` rule does the [`ConstEvaluator`](https://github.com/apache/arrow-datafusion/blob/ae0f401d89cf9dc8b717e6b95f73ed4f3be9798b/datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs#L232), the `42/0` evaluated, result in Divide by zero error.

This is a similar problem to what #8814 describes. maybe we also should not do `ConstEvaluator` for short-circuited operators.

I also do some test in datafusion-cli v34
```
DataFusion CLI v34.0.0
❯ SELECT CASE 1 WHEN 2 THEN 42/0 END;
Optimizer rule 'simplify_expressions' failed
caused by
Arrow error: Divide by zero error
❯ select 4/0;
Optimizer rule 'simplify_expressions' failed
caused by
Arrow error: Divide by zero error
❯ select 1 > 4 and 5/0 > 2;
Optimizer rule 'simplify_expressions' failed
caused by
Arrow error: Divide by zero error
```
