### ISSUE TITLE
strpos doesn't account for unicode grapheme characters

### ISSUE THREAD

**Issue by Omega359** [apache/arrow-datafusion#9052]
### Describe the bug

❯ docker run -it -v /tmp:/data datafusion-cli
DataFusion CLI v35.0.0
❯ SELECT strpos('since ̯ͅI can ̤̗do ̲̬̝th̟̟̱i̹s̹̱', 'can');
+-------------------------------------------------+
| strpos(Utf8("since ̯ͅI can ̤̗do ̲̬̝th̟̟̱i̹s̹̱"),Utf8("can")) |
+-------------------------------------------------+
| 0                                               |
+-------------------------------------------------+
1 row in set. Query took 0.067 seconds.

Should be 9.

### Expected behavior

position should account for unicode grapheme characters, not just unicode scalar values.

**Comment by Omega359** [comment]
Note that this 'bug' may not be something that can be easily fixed given the nature of unicode grapheme's. For example, I came across this insightful response for a similar postgres issue - https://stackoverflow.com/a/64889162/1695525

**Comment by alamb** [comment]
Yeah, I agree it would be interesting to hear what the usecase for this is and what the expected semantics of this call are.

**Comment by jhorstmann** [comment]
Is there any other database that implements `strpos` in terms of grapheme clusters? When I did research on string functions across databases, nearly all of them implemented it in term of scalar values. I even argued to use bytes instead, for performance, and since a position would most likely be used as input to another string function like `substring`. But I got overruled, compatibility is a pretty good argument.

**Comment by Omega359** [comment]
Probably not supported anywhere tbh. It was something I noticed when browsing the code however in looking into it for postgres and spark it seems that it's likely not something that can be easily supported. Thus I'm going to close this as essentially 'won't fix'
