### ISSUE TITLE
Projections require unique expression names error

### ISSUE THREAD

**Issue by lewiszlw** [apache/arrow-datafusion#9130]
### Describe the bug

Datafusion failed to execute `select * from (t1 cross join t2) as t cross join t3` with error message
```
Error during planning: Projections require unique expression names but the expression "t.a" at position 0 and "t.a" at position 2 have the same name. Consider aliasing ("AS") one of them.
```
I tested on sqlite3 and it return expected result.
latest commit: 840499fbd3c25bf82a6ee0641ef6888079e096da

### To Reproduce

create table t1 (a int, b int);
create table t2 (a int, b int);
create table t3 (a int, b int);
insert into t1 values (1, 2);
insert into t2 values (3, 4);
insert into t3 values (5, 6);
select * from (t1 cross join t2) as t cross join t3;

### Expected behavior

Return result like sqlite3
```
1|2|3|4|5|6
```

**Comment by Jefffrey** [comment]
Related: https://github.com/apache/arrow-datafusion/issues/6543

**Comment by Lordworms** [comment]
I want to try this one

**Comment by Lordworms** [comment]
I tested the sqllite3 and it does not support ambiguous expressions on the tmp table. But when I create a table, it could work, and the table schema turns out to add another :1 to the columns, I guess we could do what they do.
<img width="1076" alt="image" src="https://github.com/apache/arrow-datafusion/assets/48054792/e6b6e0ac-8c5e-465e-b115-9f11bfc47f55">

**Comment by Lordworms** [comment]
The rule is here,  basically, we need to implement two things
I. first one, in select * from (t1 cross join t2) as t cross join t3. if t is a tmp table and there are no other actions on that tmp table. we just ignore the 'as t' since this works
<img width="569" alt="image" src="https://github.com/apache/arrow-datafusion/assets/48054792/758e1301-6c8d-4550-bdd9-43296393c56c">
II. the rest following the design of sqlite3, when create a real table, change its schema and add a ':num' to the name of the column inorder to make this works
<img width="570" alt="image" src="https://github.com/apache/arrow-datafusion/assets/48054792/90bd5057-23fe-412f-bd45-b9e8a1b3e200">
