### ISSUE TITLE
Implement date/time -> string formatting functions

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#9147]
### Is your feature request related to a problem or challenge?

Asked about in Discord

> DataFusion doesn't have any time formatting functions, right? i.e. something like date_time.format("%d/%m/%Y")

The idea is to be able to format timestamps / dates back to different formats of strings

### Describe the solution you'd like

Implement some sort of date/time/timestamp -> string formatting function that takes a user defined formatting string (probably chrono format) and returns a string

For example the postgres `to_char` function does this:
https://www.postgresql.org/docs/current/functions-formatting.html

Spark may have a better API (I haven't researched it)

arrow-rs already has the actual formatting code in `ArrayFormatter`:
https://docs.rs/arrow/latest/arrow/util/display/struct.ArrayFormatter.html

And specify by 
https://docs.rs/arrow/latest/arrow/util/display/struct.FormatOptions.html

So this project is likely just to define a function, wire it in, and write some tests

**Comment by Omega359** [comment]
I'll work on this next if no one minds

**Comment by Omega359** [comment]
[Spark api](https://spark.apache.org/docs/latest/api/sql/#date_format) has a different name (date_format) but otherwise is very similar. I plan on having both names and have the spark one be an alias.

The pg to_char function also handles numbers which I think should be something we can either handle in this ticket or as a future improvement.

**Comment by alamb** [comment]
Thank you @universalmind303

**Comment by alamb** [comment]
Thank you @Omega359
