### ISSUE TITLE
Support select range from datetime

### ISSUE THREAD

**Issue by Lordworms** [apache/arrow-datafusion#9353]
### Is your feature request related to a problem or challenge?

<img width="1068" alt="image" src="https://github.com/apache/arrow-datafusion/assets/48054792/cd1b852b-86fb-40f7-b77e-221ce4df0335">
duckdb did it
<img width="1020" alt="image" src="https://github.com/apache/arrow-datafusion/assets/48054792/a0efa91f-9c25-435f-a713-c06e6be2ab98">

**Comment by Lordworms** [comment]
take

**Comment by Lordworms** [comment]
wait until #9352 merged

**Comment by Omega359** [comment]
Is the range function still going to be an alias of generate_series but that generate_series will now support date/time intervals such as (postgresql syntax) ?
```
SELECT generate_series('2012-06-29', '2012-07-03', '1 day'::interval);
```

**Comment by Lordworms** [comment]
> Is the range function still going to be an alias of generate_series but that generate_series will now support date/time intervals such as (postgresql syntax) ?
> 
> ```
> SELECT generate_series('2012-06-29', '2012-07-03', '1 day'::interval);
> ```

No, with #9352  I have separated the range and generate_series since they stands for different meaning in duckDB, and right now I am going to support the syntax in duckDB for datetime

**Comment by Omega359** [comment]
My understanding is that at this time DataFusion wants to maintain compatibility with postgresql syntax as much as possible which is why I was asking. That being said postgresql doesn't have a range function exactly (what they have is pretty weird tbh) so having a range function is a nice addition. I would have looked at having generate_series though support an optional 3rd param for interval though.
