### ISSUE TITLE
`/benchmark` command seems not to work

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-datafusion#9620]
### Describe the bug

I tried to run bencmark for https://github.com/apache/arrow-datafusion/pull/9593#issuecomment-1999266843

but this resulted in a failure:
https://github.com/apache/arrow-datafusion/actions/runs/8294100431/job/22698438691

`the input device is not a TTY`

**Comment by gruuya** [comment]
Thanks @Dandandan; I've encountered that problem originally and (I thought I) resolved it by [removing -ti](https://github.com/apache/arrow-datafusion/pull/9461/files#diff-1769f5787dc11c8b1f1b48288cdf3c89d25a5b5cbc6be4740bfcc70a6313ba99L281) from the tpch_dbgen docker command, after which the thing worked on our fork.

Will investigate more.

**Comment by gruuya** [comment]
It's weird that the exact same workflow works on our fork, but not here; seems to suggest a difference in some settings?
Fwiw, I inspected the setup and it seems to be using the identical os/runner/image etc versions.

Either way I opened https://github.com/apache/arrow-datafusion/pull/9626 as a potential workaround, except I can't really guarantee it works now (the command fails becuase it's still using the version from the main in the action).

**Comment by Dandandan** [comment]
Thanks @gruuya that worked 🎉 

The next failure is a missing file
https://github.com/apache/arrow-datafusion/pull/9593#issuecomment-2000970364

**Comment by gruuya** [comment]
Hmm, that's another weird one, where GHA obviously [has the adequate env var](https://github.com/apache/arrow-datafusion/actions/runs/8304225995/job/22729577627#step:5:10) but somehow the script invocation doesn't.

My best guess is that this is because the immediately preceding step (where the env vars were generated) was run in a different shell now, and so GHA somehow hasn't propagated the env vars yet to the first step (but [it does](https://github.com/apache/arrow-datafusion/actions/runs/8304225995/job/22729577627#step:7:37) to the subsequent ones).

Anyway, I've opened another potential mitigation here: https://github.com/apache/arrow-datafusion/pull/9632

Thanks for the patience!

**Comment by Dandandan** [comment]
That didn't resolve it yet :)
https://github.com/apache/arrow-datafusion/pull/9593#issuecomment-2001918666

**Comment by gruuya** [comment]
Ok, third time's the charm: https://github.com/apache/arrow-datafusion/pull/9636 🤞🏻

**Comment by Dandandan** [comment]
Thanks @gruuya 🥳

**Comment by gruuya** [comment]
I'm glad to see it working now, though I'm not that happy with the finicky nature of the development process, courtesy of GHA idiosyncrasies.

I've noted down a potential improvement to the trial-and-error dev approach here: https://github.com/apache/arrow-datafusion/issues/9638
