### ISSUE TITLE
move Floor, Gcd, Lcm, Pi to datafusion-functions

### ISSUE THREAD

**Issue by Omega359** [apache/arrow-datafusion#9861]
### Is your feature request related to a problem or challenge?

As part of https://github.com/apache/arrow-datafusion/issues/9285 move the  Floor, Gcd, Lcm, Pi functions to the new datafusion-functions crate in the new structure.

### Describe the solution you'd like

Functions are migrated to the new crate and use the new patterns as described in https://github.com/apache/arrow-datafusion/issues/9286 & https://github.com/apache/arrow-datafusion/pull/9216

**Comment by tinfoil-knight** [comment]
@Omega359 I realised while working on #9868 that some parts (eg: simplifying expressions: search `simpl_log`, `simpl_power`) of `log` & `power` functions are dependent on each other.

I think that these functions should be migrated together. Since you're already migrating the `power` function, can you also pick up the `log` function in the same PR?

**Comment by Omega359** [comment]
Oh, I just created the tickets .. I wasn't attempting to do all of them @tinfoil-knight  :) If you are working on something related feel free to take this ticket too

**Comment by tinfoil-knight** [comment]
@Omega359 I just need the `Power` function since it's dependent on `Log`.

I've opened a new issue: #9875 for it. Please update this issue to not include the `Power` function. Thank you!

**Comment by Omega359** [comment]
take

**Comment by alamb** [comment]
❤️  -- thank you @Omega359
